baseurl = "https://www.fikawow.se/"
languageCode = "sv-se"
title = "<FIKA>"
theme = "hugo-creative-theme"
googleAnalytics = ""
publishdir = "clnfrt.github.io"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Guilden FIKA"
	description = "Swedish Elysium Alliance guild"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "\\<FIKA\\> @ Elysium"

		[params.navigation.links]
			about     = "Ansök"
			services  = "Information"
			portfolio = "Nyheter"
			contact   = "Kontakta"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "\\<Fika\\>"
		subtitle   = "Swedish [Elysium](//elysium-project.org/) Alliance guild"
		buttonText = "Skriv upp dig på gofika idag!"


	# About section
	[params.about]
		headline    = "Gör Azeroth lagom igen!"
		description = "\\<FIKA\\> är en nystartad guild, belägen på den nyöppnade servern Elysium PVP. Många befintliga medlemmar kommer från guilden \\<Andromeda\\> från Nostalrius PVP. Denna gång satsar vi på en helsvensk guild, en social och trevlig miljö med välstrukturerade raids. De flesta av oss har spelat på högre nivåer i Vanilla."
		buttonText  = "Ta mig till rekryteringssidan!"


	# Service section
	[params.services]
		headline = "Information om oss"

        [[params.services.list]]
            icon = "fa-shield"
            title = "Realmplayers"
            description = "[Topping the charts](//realmplayers.com/CharacterViewer.aspx?realm=NRB&player=Skitzi)"

        [[params.services.list]]
			icon = "fa-headphones"
			title = "Discord"
			description = "[https://discord.gg/yhwaRXx](//discord.gg/yhwaRXx)"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Progress"
            description = "MC 0/8 Onyxia 0/1"

        [[params.services.list]]
            icon = "fa-clock-o"
            title = "Raidtider"
            description = "Sön/Tor 19-22"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Läs våra preliminära regler"

		[params.aside.button]
			text = "Guild/Loot-regler"
			link = "//docs.google.com/document/d/1EtvE2NDLSasN4ArWQxdwrX3eMGH0Yp2XRvErL_n8JVQ"

	# Contact section
	[params.contact]
		headline = "Lorem ipsum dolor sit amet"
		description = "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
		phone = "123-456-6789"
		email = "dev@null.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
